<?php
// $Id$

/**
 * @file
 * Vocabulary Permissions Per Role
 *
 * Allows adding to/editing terms of/removing terms from vocabularies per role.
 */

/**
 * Implementation of hook_menu_alter().
 */
function vppr_menu_alter(&$items) {
  // Add terms: http://d6.l/admin/content/taxonomy/$vid/add/term
  $items['admin/content/taxonomy/%taxonomy_vocabulary/add/term']['access callback'] = '_vppr_access_vocabulary';
  $items['admin/content/taxonomy/%taxonomy_vocabulary/add/term']['access arguments'] = array(3);
  // Reorder terms: http://d6.l/admin/content/taxonomy/$vid
  $items['admin/content/taxonomy/%taxonomy_vocabulary']['access callback'] = '_vppr_access_vocabulary';
  $items['admin/content/taxonomy/%taxonomy_vocabulary']['access arguments'] = array(3);
  // Edit and delete terms: http://d6.l/admin/content/taxonomy/edit/term/$tid - warning: there's only a tid arg!
  $items['admin/content/taxonomy/edit/term']['access callback'] = '_vppr_access_term';
  $items['admin/content/taxonomy/edit/term']['access arguments'] = array(5);
}

/**
 * VPPR's access callback for vocabularies (add and reorder terms).
 */
function _vppr_access_vocabulary($vocab) {
  if (user_access('administer taxonomy')) {
    return TRUE;
  }
  global $user;
  $perms = variable_get('vppr_perms', array(array()));
  foreach ($user->roles as $rid => $role) {
    if ($perms[$vocab->vid][$rid]) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * VPPR's access callback for term ID's (edit and delete terms).
 */
function _vppr_access_term($tid) {
  if (user_access('administer taxonomy')) {
    return TRUE;
  }
  $term = taxonomy_get_term($tid);
  // Speed up things if there is no such term.
  if (!$term) {
    return FALSE;
  }
  global $user;
  $perms = variable_get('vppr_perms', array(array()));
  foreach ($user->roles as $rid => $role) {
    if ($perms[$term->vid][$rid]) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Implementation of hook_perm().
 */
function vppr_perm() {
  return array('administer VPPR');
}

/**
 * Implementation of hook_menu().
 */
function vppr_menu() {
  $items = array();
  $items['admin/settings/vppr'] = array(
    'title' => 'Vocabulary permissions',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('vppr_form_admin_settings_vppr'),
    'access arguments' => array('administer VPPR'),
    'file' => 'vppr.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 */
function vppr_theme() {
  return array(
    'vppr_form_admin_settings_vppr' => array(
      'arguments' => array('form' => array()),
      'file' => 'vppr.admin.inc',
    ),
  );
}

